repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        stages: [commit]
        args:
          [
            "-ri",
            "--remove-duplicate-keys",
            "--ignore-init-module-imports",
            "--remove-unused-variables",
          ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
